# ██████████████████████████████████████████████████████████████
# █▄─▀█▀─▄█▄─▄█▄─▄███▄─▄▄─█─▄▄▄▄█─▄─▄─█─▄▄─█▄─▀█▄─▄█▄─▄▄─█─▄▄▄▄█
# ██─█▄█─███─███─██▀██─▄█▀█▄▄▄▄─███─███─██─██─█▄▀─███─▄█▀█▄▄▄▄─█
# ▀▄▄▄▀▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▄▄▄▄▀▄▄▄▄▄▀▀▄▄▄▀▀▄▄▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▄▄▄▀

fame-multiplier: 1.5