# ██████████████████████████████████████████████████████████████
# █▄─▀█▀─▄█▄─▄█▄─▄███▄─▄▄─█─▄▄▄▄█─▄─▄─█─▄▄─█▄─▀█▄─▄█▄─▄▄─█─▄▄▄▄█
# ██─█▄█─███─███─██▀██─▄█▀█▄▄▄▄─███─███─██─██─█▄▀─███─▄█▀█▄▄▄▄─█
# ▀▄▄▄▀▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▄▄▄▄▀▄▄▄▄▄▀▀▄▄▄▀▀▄▄▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▄▄▄▀

fame-multiplier: 1.5


# Create custom milestones here:

milestones: